name: flugir-budgie-theme
build-base: core24
base: bare
version: '0.9.4'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: A dark theme for Budgie Desktop.
description: |
  A Snap to use Flugir Budgie GTK theme, Flugir-Tela icons and FlugirDot cursors in Snap apps.
grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/FlugirDot
        - $SNAP/share/icons/Flugir-Tela
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Flugir-Budgie
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Flugir-Budgie
  
parts:
  # FlugirDot cursors, GoogleDot version 2.0.0 of 2022-10-22, Tela icons version 2024-09-04
  icon-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/Flugir-Budgie/releases/download/Flugir-Budgie-0.9.4/Flugir-Budgie-0.9.4-snapcraft-files.tar.xz
    override-build: |
      snapcraftctl build
      pwd
      ls -l
      mkdir -p $CRAFT_PART_INSTALL/share/icons
      mv -f $CRAFT_PART_INSTALL/icon-themes/FlugirDot $CRAFT_PART_INSTALL/share/icons
      mv -f $CRAFT_PART_INSTALL/icon-themes/Flugir-Tela $CRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/FlugirDot
      - share/icons/Flugir-Tela
  # Flugir-Budgie gtk theme, Qogir version 2024-05-02
  gtk-2-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/Flugir-Budgie/releases/download/Flugir-Budgie-0.9.4/Flugir-Budgie-0.9.4-snapcraft-files.tar.xz
    override-build: |
      snapcraftctl build
      pwd
      ls -l
      mkdir -p $CRAFT_PART_INSTALL/share/
      mv -f $CRAFT_PART_INSTALL/gtk-themes/gtk2 $CRAFT_PART_INSTALL/share/
    stage:
      - share/gtk2/Flugir-Budgie
  gtk-3-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/Flugir-Budgie/releases/download/Flugir-Budgie-0.9.4/Flugir-Budgie-0.9.4-snapcraft-files.tar.xz
    override-build: |
      snapcraftctl build
      pwd
      ls -l
      mkdir -p $CRAFT_PART_INSTALL/share/
      mv -f $CRAFT_PART_INSTALL/gtk-themes/themes $CRAFT_PART_INSTALL/share/
    stage:
      - share/themes/Flugir-Budgie
