name: flugir-budgie-theme
build-base: core24
base: bare
version: '2.3'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: Some themes used in Budgie Desktop and others.
description: |
  A Snap to use Flugir themes and others in Snap apps.
grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/FlugirDot
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Flugir-Budgie
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Flugir-Budgie
parts:
  FlugirDot:
    plugin: dump
    source: https://github.com/Kyuyrii/Flugir-Budgie/releases/download/Flugir-Budgie-2.3/Flugir-Budgie-2.3.tar.xz
    override-build: |
      snapcraftctl build
      pwd
      ls -l
      mkdir -p $CRAFT_PART_INSTALL/share/icons
      mv -f $CRAFT_PART_INSTALL/icons/* $CRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/
  Flugir-Budgie-GTK:
    plugin: dump
    source: https://github.com/Kyuyrii/Flugir-Budgie/releases/download/Flugir-Budgie-2.3/Flugir-Budgie-2.3.tar.xz
    override-build: |
      snapcraftctl build
      pwd
      ls -l
      mkdir -p $CRAFT_PART_INSTALL/share/gtk2
      mkdir -p $CRAFT_PART_INSTALL/share/themes
      mv -f $CRAFT_PART_INSTALL/gtk2/* $CRAFT_PART_INSTALL/share/gtk2
      mv -f $CRAFT_PART_INSTALL/themes/* $CRAFT_PART_INSTALL/share/themes
    stage:
      - share/themes
