name: flugir-budgie-theme
build-base: core24
base: bare
version: '3.1'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: Some themes used in Budgie Desktop and others.
description: |
  A Snap to use Flugir themes and others in Snap apps.
grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Bibata-Modern-Amber
        - $SNAP/share/icons/Bibata-Modern-Amber-Right
        - $SNAP/share/icons/Bibata-Modern-Classic
        - $SNAP/share/icons/Bibata-Modern-Classic-Right
        - $SNAP/share/icons/Bibata-Modern-Ice
        - $SNAP/share/icons/Bibata-Modern-Ice-Right
        - $SNAP/share/icons/Bibata-Original-Amber
        - $SNAP/share/icons/Bibata-Original-Amber-Right
        - $SNAP/share/icons/Bibata-Original-Classic
        - $SNAP/share/icons/Bibata-Original-Classic-Right
        - $SNAP/share/icons/Bibata-Original-Ice
        - $SNAP/share/icons/Bibata-Original-Ice-Right
        - $SNAP/share/icons/catppuccin-frappe-dark-cursors
        - $SNAP/share/icons/catppuccin-frappe-light-cursors
        - $SNAP/share/icons/Colloid-Catppuccin
        - $SNAP/share/icons/Colloid-Catppuccin-Dark
        - $SNAP/share/icons/Colloid-Catppuccin-Light
        - $SNAP/share/icons/Fluent
        - $SNAP/share/icons/Fluent-dark
        - $SNAP/share/icons/Fluent-light
        - $SNAP/share/icons/FlugirDot
        - $SNAP/share/icons/GoogleDot-Black
        - $SNAP/share/icons/GoogleDot-Blue
        - $SNAP/share/icons/GoogleDot-Red
        - $SNAP/share/icons/GoogleDot-White
        - $SNAP/share/icons/Papirus
        - $SNAP/share/icons/Papirus-aliz
        - $SNAP/share/icons/Papirus-Dark
        - $SNAP/share/icons/Papirus-dark-aliz
        - $SNAP/share/icons/Papirus-dark-pueril
        - $SNAP/share/icons/Papirus-dark-sea
        - $SNAP/share/icons/Papirus-Light
        - $SNAP/share/icons/Papirus-light-aliz
        - $SNAP/share/icons/Papirus-light-pueril
        - $SNAP/share/icons/Papirus-light-sea
        - $SNAP/share/icons/Papirus-pueril
        - $SNAP/share/icons/Papirus-sea
        - $SNAP/share/icons/Qogir
        - $SNAP/share/icons/Qogir-Dark
        - $SNAP/share/icons/Qogir-Light
        - $SNAP/share/icons/Qogir-Manjaro
        - $SNAP/share/icons/Qogir-Manjaro-Dark
        - $SNAP/share/icons/Qogir-Manjaro-Light
        - $SNAP/share/icons/Qogir-Ubuntu
        - $SNAP/share/icons/Qogir-Ubuntu-Dark
        - $SNAP/share/icons/Qogir-Ubuntu-Light
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Colloid-Compact-Catppuccin
        - $SNAP/share/gtk2/Colloid-Dark-Compact-Catppuccin
        - $SNAP/share/gtk2/Colloid-Light-Compact-Catppuccin
        - $SNAP/share/gtk2/Fluent
        - $SNAP/share/gtk2/Fluent-compact
        - $SNAP/share/gtk2/Fluent-Dark
        - $SNAP/share/gtk2/Fluent-Dark-compact
        - $SNAP/share/gtk2/Fluent-Light
        - $SNAP/share/gtk2/Fluent-Light-compact
        - $SNAP/share/gtk2/Flugir-Budgie
        - $SNAP/share/gtk2/Flugir-Matcha-aliz
        - $SNAP/share/gtk2/Flugir-Matcha-azul
        - $SNAP/share/gtk2/Flugir-Matcha-dark-aliz
        - $SNAP/share/gtk2/Flugir-Matcha-dark-azul
        - $SNAP/share/gtk2/Flugir-Matcha-dark-pueril
        - $SNAP/share/gtk2/Flugir-Matcha-dark-sea
        - $SNAP/share/gtk2/Flugir-Matcha-light-aliz
        - $SNAP/share/gtk2/Flugir-Matcha-light-azul
        - $SNAP/share/gtk2/Flugir-Matcha-light-pueril
        - $SNAP/share/gtk2/Flugir-Matcha-light-sea
        - $SNAP/share/gtk2/Flugir-Matcha-pueril
        - $SNAP/share/gtk2/Flugir-Matcha-sea
        - $SNAP/share/gtk2/Qogir
        - $SNAP/share/gtk2/Qogir-Dark
        - $SNAP/share/gtk2/Qogir-Light
        - $SNAP/share/gtk2/Qogir-Manjaro
        - $SNAP/share/gtk2/Qogir-Manjaro-Dark
        - $SNAP/share/gtk2/Qogir-Manjaro-Light
        - $SNAP/share/gtk2/Qogir-Ubuntu
        - $SNAP/share/gtk2/Qogir-Ubuntu-Dark
        - $SNAP/share/gtk2/Qogir-Ubuntu-Light
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Colloid-Compact-Catppuccin
        - $SNAP/share/themes/Colloid-Dark-Compact-Catppuccin
        - $SNAP/share/themes/Colloid-Light-Compact-Catppuccin
        - $SNAP/share/themes/Fluent
        - $SNAP/share/themes/Fluent-compact
        - $SNAP/share/themes/Fluent-Dark
        - $SNAP/share/themes/Fluent-Dark-compact
        - $SNAP/share/themes/Fluent-Light
        - $SNAP/share/themes/Fluent-Light-compact
        - $SNAP/share/themes/Flugir-Budgie
        - $SNAP/share/themes/Flugir-Matcha-aliz
        - $SNAP/share/themes/Flugir-Matcha-azul
        - $SNAP/share/themes/Flugir-Matcha-dark-aliz
        - $SNAP/share/themes/Flugir-Matcha-dark-azul
        - $SNAP/share/themes/Flugir-Matcha-dark-pueril
        - $SNAP/share/themes/Flugir-Matcha-dark-sea
        - $SNAP/share/themes/Flugir-Matcha-light-aliz
        - $SNAP/share/themes/Flugir-Matcha-light-azul
        - $SNAP/share/themes/Flugir-Matcha-light-pueril
        - $SNAP/share/themes/Flugir-Matcha-light-sea
        - $SNAP/share/themes/Flugir-Matcha-pueril
        - $SNAP/share/themes/Flugir-Matcha-sea
        - $SNAP/share/themes/Qogir
        - $SNAP/share/themes/Qogir-Dark
        - $SNAP/share/themes/Qogir-Light
        - $SNAP/share/themes/Qogir-Manjaro
        - $SNAP/share/themes/Qogir-Manjaro-Dark
        - $SNAP/share/themes/Qogir-Manjaro-Light
        - $SNAP/share/themes/Qogir-Ubuntu
        - $SNAP/share/themes/Qogir-Ubuntu-Dark
        - $SNAP/share/themes/Qogir-Ubuntu-Light
  
parts:
  icon-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/Flugir-Budgie/releases/download/Flugir-Budgie-3.0/flugir-budgie-snapcraft-3.0.tar.xz
    organize:
      usr/share/icons: share/icons
    prime:
      - share/icons/

  gtk-2-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/Flugir-Budgie/releases/download/Flugir-Budgie-3.0/flugir-budgie-snapcraft-3.0.tar.xz
    organize:
      usr/share/themes: share/gtk2
    prime:
      - share/gtk2/*/gtk-2.0

  gtk-3-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/Flugir-Budgie/releases/download/Flugir-Budgie-3.0/flugir-budgie-snapcraft-3.0.tar.xz
    organize:
      usr/share/themes: share/themes
    prime:
      - share/themes/*/gtk-3.0
      - share/themes/*/gtk-4.0
