name: flugir-budgie-theme
build-base: core24
base: bare
version: '1.0'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: Some themes used in Budgie Desktop.
description: |
  A Snap to use Flugir themes and others in Snap apps.
grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/FlugirDot
        - $SNAP/share/icons/Flugir-Papirus
        - $SNAP/share/icons/Flugir-Papirus-Dark
        - $SNAP/share/icons/Flugir-Papirus-Light
        - $SNAP/share/icons/Flugir-Tela
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Flucillo
        - $SNAP/share/gtk2/Flucillo-Slim
        - $SNAP/share/gtk2/Fluent
        - $SNAP/share/gtk2/Fluent-compact
        - $SNAP/share/gtk2/Fluent-Dark
        - $SNAP/share/gtk2/Fluent-Dark-compact
        - $SNAP/share/gtk2/Fluent-Light
        - $SNAP/share/gtk2/Fluent-Light-compact
        - $SNAP/share/gtk2/Flugir-Budgie
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Flucillo
        - $SNAP/share/themes/Flucillo-Slim
        - $SNAP/share/themes/Fluent
        - $SNAP/share/themes/Fluent-compact
        - $SNAP/share/themes/Fluent-Dark
        - $SNAP/share/themes/Fluent-Dark-compact
        - $SNAP/share/themes/Fluent-Light
        - $SNAP/share/themes/Fluent-Light-compact
        - $SNAP/share/themes/Flugir-Budgie
  
parts:
  # FlugirDot cursors, GoogleDot version 2.0.0 of 2022-10-22, Papirus icons extracted in 2025-02-25
  icon-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/Flugir-Budgie/releases/download/Flugir-Budgie-1.0/Flugir-Budgie-1.0-snapcraft-files.tar.xz
    override-build: |
      snapcraftctl build
      pwd
      ls -l
      mkdir -p $CRAFT_PART_INSTALL/share/icons
      mv -f $CRAFT_PART_INSTALL/icon-themes/* $CRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/FlugirDot
      - share/icons/Flugir-Papirus
      - share/icons/Flugir-Papirus-Dark
      - share/icons/Flugir-Papirus-Light
      - share/icons/Flugir-Tela
  # Gtk themes, Qogir extracted in 2025-02-24, Pocillo deb version 0.21.0
  gtk-2-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/Flugir-Budgie/releases/download/Flugir-Budgie-1.0/Flugir-Budgie-1.0-snapcraft-files.tar.xz
    override-build: |
      snapcraftctl build
      pwd
      ls -l
      mkdir -p $CRAFT_PART_INSTALL/share/
      mv -f $CRAFT_PART_INSTALL/gtk-themes/gtk2 $CRAFT_PART_INSTALL/share/
    stage:
      - share/gtk2/Flucillo
      - share/gtk2/Flucillo-Slim
      - share/gtk2/Fluent
      - share/gtk2/Fluent-compact
      - share/gtk2/Fluent-Dark
      - share/gtk2/Fluent-Dark-compact
      - share/gtk2/Fluent-Light
      - share/gtk2/Fluent-Light-compact
      - share/gtk2/Flugir-Budgie
  gtk-3-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/Flugir-Budgie/releases/download/Flugir-Budgie-1.0/Flugir-Budgie-1.0-snapcraft-files.tar.xz
    override-build: |
      snapcraftctl build
      pwd
      ls -l
      mkdir -p $CRAFT_PART_INSTALL/share/
      mv -f $CRAFT_PART_INSTALL/gtk-themes/themes $CRAFT_PART_INSTALL/share/
    stage:
      - share/themes/Flucillo
      - share/themes/Flucillo-Slim
      - share/themes/Fluent
      - share/themes/Fluent-compact
      - share/themes/Fluent-Dark
      - share/themes/Fluent-Dark-compact
      - share/themes/Fluent-Light
      - share/themes/Fluent-Light-compact
      - share/themes/Flugir-Budgie
